### ISSUE TITLE
Failed to execute 'clone' on 'Response'

### ISSUE THREAD

**Issue by chapmanio** [mswjs/msw-storybook-addon#143]
Hello,

I appreciate this may be a beta/v8 thing but I wanted to highlight it in case there is something wrong (or I'm doing something wrong).

```
"@storybook/react-vite": "^8.0.4",
"msw": "^2.2.10",
"msw-storybook-addon": "2.0.0-beta.1",
```

When running a story with mocked data, e.g.:

```tsx
const meta: Meta<typeof ComponentName> = {
  component: ComponentName
  parameters: {
    msw: {
      handlers: [
        http.get('/api/url', HttpResponse.json({ example: 'data' }))
      ],
    },
  },
};

export const FirstStory: Story = {
  args: {
    fakeProp: 'fake-data',
  }
}

export const SecondStory: Story = {
  args: {
    fakeProp: 'fake-data',
  }
  parameters: {
    msw: {
      handlers: [
        http.get('/api/url', HttpResponse.json({ example: 'different-data' }))
      ],
    },
  },
}
```

Viewing either story on their own is fine, **however**, if you run `SecondStory`, then click to run `FirstStory`, then go _back_ to `SecondStory` there will be an error in the console:

```tsx
msw-storybook-addon.js?v=2576b988:1931 
Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Response': Response body is already used
    at Object.onMockedResponse (msw-storybook-addon.js?v=2576b988:1931:48)
    at handleRequest (msw-storybook-addon.js?v=2576b988:1093:114)
    at async msw-storybook-addon.js?v=2576b988:1920:11
```

Pointing to this code:

```tsx
  async onMockedResponse(response, { handler, parsedResult }) {
    const responseClone = response.clone();  // <-- HERE
    const responseCloneForLogs = response.clone();
```

I've tried different ways of setting the handlers but I always get this response when coming back to the story.

**Comment by yannbf** [comment]
Hey everyone! Finally the major version is out. Sorry for such a long wait, I had to make sure the addon aligned with Storybook 8 and worked correctly in the portable stories (using stories in Vitest,Jest) scenario.

Please check the release notes, try it out and provide feedback in case issues arise:
https://github.com/mswjs/msw-storybook-addon/releases/tag/v2.0.0

Let me know if your issue is not resolved, feel free to reopen it and I'll take a look.

Thanks!
