### ISSUE TITLE
mock service worker integration in storybook-build

### ISSUE THREAD

**Issue by pedrohba1** [mswjs/msw-storybook-addon#29]
First of all, thanks for creating this addon, It's being really useful overall. However, I have a specific use case where when building storybook with the default `build-storybook` command, which generates the `storybook-static` folder, I want to be able to get data from the mock service provider.
Right now, when the build finishes, the mock service provider doesn't work (can't fetch any data). 

How could I make it work within the build?

I want this behaviour because I can just send to my clients a link to check how the frontend is looking right now, which is the storybook build, and having no mocks in it will provide them nothing useful.

**Comment by kettanaito** [comment]
Actually, as I discovered that we have a wildcard version range specified for the `msw` peer dependency, as long as you install `msw@0.29.0`, you'll have a build support in Storybook, as 0.29.0 includes the fallback mode feature that enables such support. 

Please update and let us know. Thanks.

**Comment by hyogman** [comment]
Hi @kettanaito, 

Thank you for the awesome library 🎉 

Could you point me to some docs or post here on how to set up `msw` and `msw-storybook` for a storybook static site?

**Comment by kettanaito** [comment]
Hey, @hyogman. Thank you for the kind words!

Static builds support is enabled by default since `msw@0.29.0`. As long as you've got that, or higher, version installed, your request handlers will work in static Storybook builds. 

You can follow the [MSW Storybook Add-on documentation](https://msw-sb.netlify.app/) to set the add-on in your Storybook project. There are no extra things necessary.

Note that static support affects static Storybook builds viewed under a `file://` protocol (i.e. opening the built `index.html` in your browser). When _serving_ a build of any kind, MSW worked and works as expected.

**Comment by oanaOM** [comment]
Hey @hyogman and @kettanaito. I'm encountering the same issue: the mock service provider isn't being picked up at build time. Upgrading to `msw@0.29.0` didn't worked so was wondering if there is anything I need to look after?

**Comment by kettanaito** [comment]
@oanaOM we are currently working on improving the Storybook add-on, which will include the exact dependency versions to ensure static build support. If updating to `msw@0.29.0` didn't help, I recommend waiting for the next release of this add-on. Thanks.

**Comment by oanaOM** [comment]
@kettanaito ohh cool, thanks for letting me know! Do you know what is the timeline for the next release?

**Comment by josh-biddick** [comment]
@kettanaito - I'm on `msw@0.31.0` and still unable to see this working. This would be great feature to have! Keep up the epic work.

**Comment by kettanaito** [comment]
Hey, @josh-biddick. Could you please share the exact error you're getting during the build? At this point, the static build support should be functional, so the issues you experience may be of a different nature. I'd like to learn more.

**Comment by tomcarter17** [comment]
@kettanaito - I'm having a similar issue using the latest versions of `msw` (`0.42.2`) and this addon (`1.6.3`).

I'm seeing the mocking behaviour perfectly functional when running the development Storybook server, but when serving a static build through `http-server`, it appears that the addon doesn't initialise at all. I can't see any errors to be able to show here either unfortunately.

The only thing I can think of that's different to the setup in the docs is that we're using the Storybook public folder instead of the regular app one, is it possible this could make a difference? The `mockServiceWorker.js` file is correctly set up in `.storybook/public/mockServiceWorker.js`.

`"storybook": "start-storybook -s .storybook/public ./styles/images -p 6006",`

Is there any more information I can provide for debugging purposes, or any advice on what could be incorrect in terms of configuration? Otherwise if confirmed, would it be possible to re-open this issue?

**Comment by kettanaito** [comment]
Looks like you're not serving the worker script. Make sure:

- You have generated the script via `npx msw init <PUBLIC_DIR>`;
- You are using the `-s` flag for Storybook CLI to serve the public dir.

**Comment by yannbf** [comment]
Great to know you figured that out @tomcarter17! I'd recommend using the new notation of [staticDirs](https://storybook.js.org/docs/react/configure/images-and-assets#serving-static-files-via-storybook-configuration) which would have avoided such issue in the first place, as it's shared between dev and build in Storybook!
