### ISSUE TITLE
onUnhandledRequest drastically increasing execution time

### ISSUE THREAD

**Issue by stephan-noel-primer** [mswjs/msw-storybook-addon#37]
### Problem
Execution of visual tests on Chromatic goes from 3 minutes on average to around 18 minutes

Changing the following code: 

```javascript
 initializeWorker({
   onUnhandledRequest(req) {
     // Only some API requests should be mocked
     if (!req.url.href.startsWith(myapi(''))) {
       return;
     }
     console.error(
       'Found an unhandled %s request to %s',
       req.method,
       req.url.href,
     );

    throw new Error(
      'Unhandled request, please ensure you are mocking the correct endpoints',
    );
  },
});
```

to simply: 

```javascript
 initializeWorker();
```

fixed the issue.

I'm not sure if the problem is with this addon, with msw itself, or with how the integration is being done.  If I want to workaround this and provide a fallback request handler to setupServer, I can't because there is no way to forward options to setupServer.

### Version info:

**msw-storybook-addon**: 1.1.0
**msw**: 0.30.0:

**Comment by kettanaito** [comment]
Hey, @stephan-noel-primer. Thank you for reaching out. 

I can suspect the suggestions logic in MSW that can be the culprit here. Whenever there's an unhandled request, MSW looks up a list of suggested request handlers to account for typos and method/operation kind mismatches to improve the DX. This can be an expensive operation given a large number of handlers. 

Your approach above is sensible. Perhaps we should consider disabling the handler suggestions as an option if that's proven to be the performance bottleneck. To debug this, I recommend forking MSW, removing the [suggestions](https://github.com/mswjs/msw/blob/321d8c1c1a17d5bab7b976c6bb0d195698230be6/src/utils/request/onUnhandledRequest.ts#L141-L147), linking it to the `msw-storybook-addon` and using its local built to see if there's any performance impact.

**Comment by kettanaito** [comment]
MSW has long stopped shipping `js-lavenshtein` for request handler suggestions. Using `onUnhandledRequest` does not affect MSW performance now.
